export { Recomendacion }from '../modelo/recomendacion.model'
export { Lista }from '../modelo/lista.model'
export { Candidato }from '../modelo/candidato.model'
export { Valor }from '../modelo/valor.model'
export { Usuario }from '../modelo/usuario.model'
export { ProcesoExtraccion } from '../modelo/proceso-extraccion.model'
export { Error } from '../modelo/error.model'
export { HistorialProcesoExtraccion } from '../modelo/historial-proceso-extraccion.model'
